#!/bin/bash
# Regenerate the relaunch script for every running decision arm, from the running
# processes themselves.
#
# Why regenerate rather than retype
# ---------------------------------
# The arms must be restarted to pick up the vectorised sum-product DP (2.57x on the
# DP, which is ~90% of a step).  Restarting is only safe if every argument is
# reproduced exactly, so the command lines are read from `/proc/<pid>/cmdline` and
# `--resume <out>/resume.pt` is appended -- the driver loads the checkpoint and
# continues from the recorded step, and the batch stream is deterministic in the
# seed, so the trajectory is continuous.
#
# Each arm's own CUDA_VISIBLE_DEVICES is read from `/proc/<pid>/environ` too, since
# they are spread over MIG slices and a full GPU and must not be shuffled.
#
# Usage:  bash tools/regenerate_relaunch.sh > /mnt/cunyuliu/rna-jepa/relaunch_arms.sh
set -u
PY=/home/cunyuliu/miniconda3/envs/lucaone/bin/python

echo "#!/bin/bash"
echo "# Generated by tools/regenerate_relaunch.sh -- restarts every arm from its"
echo "# own checkpoint so it picks up the vectorised sum-product DP."
echo "set -u"
echo "export PYTHONPATH=/mnt/cunyuliu/pylibs:/home/cunyuliu/rna-jepa/src"
echo "export TMPDIR=/mnt/cunyuliu/tmp"
echo "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"
echo "export OMP_NUM_THREADS=2"
echo "cd /home/cunyuliu/rna-jepa || exit 1"
echo "launch() {"
echo "  local tag=\"\$1\"; local dev=\"\$2\"; local log=\"\$3\"; shift 3"
echo "  echo \"=== relaunch \$tag on \$dev \$(date '+%T') -> \$log ===\""
echo "  CUDA_VISIBLE_DEVICES=\"\$dev\" setsid nohup $PY -m rnajepa.train_decision \"\$@\" \\"
echo "      > \"\$log\" 2>&1 < /dev/null &"
echo "  sleep 2"
echo "}"
echo

for pid in $(pgrep -f 'rnajepa.train_decision' | sort -n); do
  [ -r "/proc/$pid/cmdline" ] || continue
  cmd="$(tr '\0' ' ' < /proc/$pid/cmdline)"
  case "$cmd" in *rnajepa.train_decision*) ;; *) continue;; esac
  dev="$(tr '\0' '\n' < /proc/$pid/environ | sed -n 's/^CUDA_VISIBLE_DEVICES=//p')"
  out="$(printf '%s\n' "$cmd" | sed -n 's/.*--out \([^ ]*\).*/\1/p')"
  arm="$(printf '%s\n' "$cmd" | sed -n 's/.*--arm \([^ ]*\).*/\1/p')"
  [ -n "$out" ] || { echo "# skip pid $pid: no --out"; continue; }
  [ -n "$dev" ] || { echo "# skip pid $pid: no CUDA_VISIBLE_DEVICES"; continue; }
  if [ ! -f "$out/resume.pt" ]; then
    echo "# skip pid $pid ($arm): no checkpoint at $out/resume.pt"
    continue
  fi
  # strip the python executable and "-m rnajepa.train_decision", keep the args
  args="${cmd#*rnajepa.train_decision }"
  tag="$(basename "$out")"
  stripped="$(printf '%s' "$tag" | sed 's/_[0-9]\{8\}T[0-9]\{6\}$//')"
  # Reuse the log the monitor and the snapshot job already look for, so the run
  # keeps one continuous history instead of starting a second file.
  log="/mnt/cunyuliu/rna-jepa/runs/$tag.log"
  [ -f "/mnt/cunyuliu/rna-jepa/runs/$stripped.log" ] \
      && log="/mnt/cunyuliu/rna-jepa/runs/$stripped.log"
  printf 'launch "%s" "%s" "%s" %s --resume "%s/resume.pt"\n' \
      "$tag" "$dev" "$log" "$args" "$out"
  echo "#   was pid $pid"
done
